### PR TITLE
Setup basic firewall

### LINKED ISSUE #69: Too many ports exposed to remote connections
The voting machine is composed of many software parts. Some of them listen to one or many ports on both the loopback network interface and other public-facing interfaces. Although the security of the voting mecanism shouldn't rely on preventing access to the machine itself, it is still a good idea to lower the attack surface.

Here is a list of all processes listening to TCP or UDP ports.

```
root@local:~# netstat -pluton
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name Timer
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      706/rpcbind      off (0.00/0/0)
tcp        0      0 0.0.0.0:28017           0.0.0.0:*               LISTEN      1128/mongod      off (0.00/0/0)
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1764/sshd        off (0.00/0/0)
tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN      1041/beam.smp    off (0.00/0/0)
tcp        0      0 0.0.0.0:55672           0.0.0.0:*               LISTEN      1041/beam.smp    off (0.00/0/0)
tcp        0      0 127.0.0.1:8545          0.0.0.0:*               LISTEN      1834/geth        off (0.00/0/0)
tcp        0      0 0.0.0.0:46307           0.0.0.0:*               LISTEN      754/rpc.statd    off (0.00/0/0)
tcp        0      0 0.0.0.0:49414           0.0.0.0:*               LISTEN      1041/beam.smp    off (0.00/0/0)
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      1128/mongod      off (0.00/0/0)
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      1243/redis-server 1 off (0.00/0/0)
tcp6       0      0 :::111                  :::*                    LISTEN      706/rpcbind      off (0.00/0/0)
tcp6       0      0 :::80                   :::*                    LISTEN      1378/apache2     off (0.00/0/0)
tcp6       0      0 :::4369                 :::*                    LISTEN      1077/epmd        off (0.00/0/0)
tcp6       0      0 :::22                   :::*                    LISTEN      1764/sshd        off (0.00/0/0)
tcp6       0      0 :::40886                :::*                    LISTEN      754/rpc.statd    off (0.00/0/0)
tcp6       0      0 :::3000                 :::*                    LISTEN      2286/nodejs      off (0.00/0/0)
tcp6       0      0 :::443                  :::*                    LISTEN      1378/apache2     off (0.00/0/0)
tcp6       0      0 :::30303                :::*                    LISTEN      1834/geth        off (0.00/0/0)
tcp6       0      0 :::5672                 :::*                    LISTEN      1041/beam.smp    off (0.00/0/0)
udp        0      0 0.0.0.0:10841           0.0.0.0:*                           635/dhclient     off (0.00/0/0)
udp        0      0 0.0.0.0:873             0.0.0.0:*                           706/rpcbind      off (0.00/0/0)
udp        0      0 127.0.0.1:930           0.0.0.0:*                           754/rpc.statd    off (0.00/0/0)
udp        0      0 0.0.0.0:40331           0.0.0.0:*                           754/rpc.statd    off (0.00/0/0)
udp        0      0 0.0.0.0:68              0.0.0.0:*                           635/dhclient     off (0.00/0/0)
udp        0      0 0.0.0.0:111             0.0.0.0:*                           706/rpcbind      off (0.00/0/0)
udp6       0      0 :::873                  :::*                                706/rpcbind      off (0.00/0/0)
udp6       0      0 :::50384                :::*                                754/rpc.statd    off (0.00/0/0)
udp6       0      0 :::26304                :::*                                635/dhclient     off (0.00/0/0)
udp6       0      0 :::111                  :::*                                706/rpcbind      off (0.00/0/0)
```

Here is a list of TCP ports open to connection from outside the voting machine.

```
$ nmap 192.168.50.42 -p-

Starting Nmap 7.12 ( https://nmap.org ) at 2016-10-15 17:58 CEST
Nmap scan report for local.cocorico.cc (192.168.50.42)
Host is up (0.00036s latency).
Not shown: 65521 closed ports
PORT      STATE SERVICE
22/tcp    open  ssh
80/tcp    open  http
111/tcp   open  rpcbind
443/tcp   open  https
3000/tcp  open  ppp
4369/tcp  open  epmd
5672/tcp  open  amqp
15672/tcp open  unknown
27017/tcp open  mongod
28017/tcp open  mongod
30303/tcp open  unknown
46307/tcp open  unknown
49414/tcp open  unknown
55672/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 2.65 seconds

```

In order to lower the number of ports exposed to the public, we should:
- Shut down any software that is not absolutely required (eg. Redis);
- Configure softwares so that they listen on the minimum number of interfaces and ports (eg. Mongodb, RabbitMQ);
- Add a firewall (eg. iptables) to allow remote connections to whitelisted ports only.

### PR DESCRIPTION
**Pull request by YoannAubineau**
Fixes #69

### CODE REVIEW

**Review by JMLX42 — CHANGES_REQUESTED** [review]
We should also allow the 80 port (and close 443) when http_protocol_prefix != https.

**Comment by YoannAubineau** [comment]
> We should also allow the 80 port (and close 443) when http_protocol_prefix != https.

Done

**Review by JMLX42 — APPROVED** [review]

**Comment by JMLX42** [comment]
I'mnot sure I understand this comment:

```
# Firewall must be set-up last so as to not interfere with any other
# provisionings. For example, provisionning of RabbitMQ may needsto access
# its admin web interface.
```

When we provision a 2nd time, the firewall is in place already.
It's pretty much like if it was installed first.
Why does it work then?

There is a typo ("needsto" instead of "needs to") in that comment that needs fixing.

Finally I think you forgot to remove the default "allow everything" iptable rule:

```
$ iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere             icmp echo-request
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
```

**Comment by JMLX42** [comment]
> Finally I think you forgot to remove the default "allow everything" iptable rule:

Maybe not.... See #77 : HTTP was closed when `http_protocol_prefix == 'https'`.

**Comment by YoannAubineau** [comment]
> When we provision a 2nd time, the firewall is in place already.
> It's pretty much like if it was installed first.
> Why does it work then?

True. It does not make any difference.

What I had in mind is the next-to-come DLX thing for webhooks which requires RabbitMQ queues to be setup at provisioning time, both through AMQP on port 5672 and its web API on port 15672.

Now, I am not sure how to handle this interdependency. I guess I will have to flush the firewall rules as a first provisioning step and reset them when everything is setup. What do you think?

**Comment by JMLX42** [comment]
> Now, I am not sure how to handle this interdependency. I guess I will have to flush the firewall rules as a first provisioning step and reset them when everything is setup. What do you think?

Provisioning is idempotent. If the opened ports are required only upon installation of RabbitMQ, then the following provisioning should not require them because RabbitMQ is already installed.
Did I get this right?

**Comment by YoannAubineau** [comment]
Actually, the provisioning is ran from 'inside' the machine, through SSH. The firewall does not interfere at all.

**Pull request merged**
